### PR TITLE
Add  the Plezi framework and minor updates

### PR DESCRIPTION
**Pull request by boazsegev**
I added [the Plezi framework](http://www.plezi.io).

Granted, it’s more Websocket oriented and it’s versioning system is still a development versioning system… but I was using  development versioning with `CombinePDF` for more than two years before I published version 1.0, so it’s more about conservatism, design and development speed than usability.

I also fixed the scripts so that `bash` runs them under `ruby` (instead of `bash`). This might be OS dependent, but this solution works on my macOS and Linux machines.

Lastly, I removed the `dev` Sinatra and Hanami references. Both Hanami 1.0 and Sinatra 2.0 were released.

Thanks for a cool benchmarking tool. Definitely gave me some insights that I hope to implement.

B.

### CODE REVIEW

**Comment by boazsegev** [comment]
Hi @luislavena ,

Sorry about that, I didn't notice it was updated.

I rolled the data back to the original data. I hope this helps.

Thanks!
B.

**Comment by boazsegev** [comment]
Hi @luislavena ,

As requested, there aren't any changes to the readme except for the new framework.

According to the ["files changed" data](https://github.com/luislavena/bench-micro/pull/23/files) It's safe to merge.

Thanks!
  Bo.

**Comment by luislavena** [comment]
Hello @boazsegev, can you rebase against master? I see changes against hamani that aren't unrelated to what you're submitting in this PR.

If you can also squash the commits will be much appreciated.

Thank you.

**Comment by boazsegev** [comment]
Hi @luislavena ,

Sure I can rebases and remove all the changes except the ones related to Plezi... but, are you sure you don't want to keep these changes?

Both Hanami 1.0 and Sinatra 2.0 were released. My change simply updates these frameworks to use their production versions instead of the (previous) development versions.

Let me know if you want me to clear these out.

**Comment by luislavena** [comment]
You're right, was confused by recent changes into master about these frameworks.

Please squash those changes in separate commits from Plezi.

Thank you. :heart: :heart: :heart:

**Comment by boazsegev** [comment]
Done ☺️

Rebased and squashed into three commits - Shebang, Hanami and Sinatra versions, an Plezi. 👍🏻

I couldn't untangle the Gemfile changes (adding Plezi and updating the Hanami and Sinatra versions), since Plezi was already present when I removed the development versions 😕, I hope it's okay.

Thank you 🙏🏻

**Comment by luislavena** [comment]
Thank you @boazsegev, changes are now merged, will update README numbers shortly.

**Comment by boazsegev** [comment]
🎉
Thanks 🙏🏻

**Pull request merged**
