### PR TITLE
Remove extra matcher from Syro app

### PR DESCRIPTION
**Pull request by soveran**

### CODE REVIEW

**Comment by jeremyevans** [comment]
Won't this return `Hello World` for all `GET` requests, not just `GET /` requests?  If so, that's not a fair benchmark, apps are supposed to check the path and return 404 for non `GET /` requests.

**Comment by soveran** [comment]
Hey @jeremyevans, yes, I changed it because `get` already checks for `root?`. The matchers in Syro are more strict, and I think eventually I'll use it in Cuba too. It was modeled after how I structure applications, and I'm happy with that behaviour so far. Let me know what you think!

**Comment by jeremyevans** [comment]
Ah, then it should be fine.

**Comment by luislavena** [comment]
@soveran thank you. I've merged your change and also updated Syro to 2.0 and benchmarks to reflect the results.

Cheers.

**Comment by luislavena** [comment]
@jeremyevans to respond to your question:

```
$ bundle exec rackup apps/syro.ru
...
$ curl -i localhost:9292
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 12

Hello World!
...
$ curl -i localhost:9292/foo
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
```

So it confirms @soveran statement.

Cheers.

**Pull request merged**
