### PR TITLE
Add Watts, minor table formatting cleanup. 

### PR DESCRIPTION
**Pull request by pete**
Hi!  This pull request is for adding Watts, a very small Ruby web framework first released in 2010.  It has been in continuous use since, and has remained stable.  As of 1.0.4¹, it seems to be the speediest framework on the list, not far behind bare rack.

I made two other commits, one to fix the formatting on the right column of the table when a number ended in a zero, and one to update the README.md to include the new numbers and a link to the Watts repo and app in the list.  (I suspect you'll want to re-run the benchmark anyway, since I didn't alter the machine specs and it probably isn't desirable to to trust performance numbers from the author of the framework.)  It merges cleanly with the other pull request that adds newark to the list.

¹ 1.0.3 and earlier had code to instantiate a `Rack::Response` on-demand, but I was instantiating it manually anyway in `Watts::Resource#initialize`, which of course put its performance slightly behind that of `rack-response.ru`.

### CODE REVIEW

**Comment by pete** [comment]
As a side note, thanks for writing this.  I ran into it while I was trying to build something similar, and I probably would not have built something quite as nice.  It also illuminated the above-mentioned bug, which I wouldn't have noticed if I hadn't profiled to see where the expensive bits were.

**Comment by luislavena** [comment]
@pete sorry for the delayed response.

I just merged Rack 2 app frameworks.

Can you update your branch against master?

Thank you.

**Comment by pete** [comment]
@luislavena Sure thing, should only take a minute.

**Comment by luislavena** [comment]
Thank you.

Also do not modify results in README as I'll run those again once merged your changes.

**Comment by pete** [comment]
Done!  Thanks!

**Pull request closed without merging**
