### PR TITLE
Add grape framework to list

### PR DESCRIPTION
**Pull request by davydovanton**

### CODE REVIEW

**Comment by luislavena** [comment]
Hello,

Thank you for the pull request, however seems Grape sends a JSON response (and thus does JSON serialization) which is different from what all the other frameworks and simple apps are doing.

Ideally Grape should be sending the same plain text response like the others in order to be a *fair* comparison.

@davydovanton can you check if that is possible? Thank you.

**Comment by davydovanton** [comment]
@luislavena nice point. I agree with you and I fixed grape app. Now it returns only string

**Comment by luislavena** [comment]
Added, thank you @davydovanton, will update benchmark table soon.

Cheers.

**Comment by davydovanton** [comment]
Super! Thanks for merge 👍

**Comment by davydovanton** [comment]
@luislavena wow, I checked results and grape is very slow 😞

**Comment by luislavena** [comment]
@davydovanton it allocates and does a bunch of thing before reaching out the actual code, which could explain why is slower than others. 

There are interesting concepts for building web applications that *in theory* should be good yet in practice (due code complexity or external dependencies) ends being slower than the thing they tried to solve.

But yeah, :disappointed:

**Pull request merged**
